version: '3.7'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - internal

x-deconcentrator: &deconcentrator
  <<: *defaults
  image: registry.elitehost.biz/beuthmaster/masterprojekt/deconcentrator:0.0.1
  environment:
    - SECRET_KEY_FILE=/run/secrets/secret-key
    - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
  secrets:
    - secret-key
    - postgres-passwd
  depends_on:
    - redis
    - memcached
    - rabbitmq
    - postgres

services:
  uwsgi:
    <<: *deconcentrator
    volumes:
      - static:/mnt/static

  worker:
    <<: *deconcentrator
    command: celery -A deconcentrator worker

  redis:
    <<: *defaults
    image: redis:alpine
    command: redis-server --maxmemory 16mb --maxmemory-policy allkeys-lru

  memcached:
    <<: *defaults
    image: memcached:alpine
    command: memcached -m 16

  rabbitmq:
    <<: *defaults
    image: rabbitmq:alpine

  postgres:
    <<: *defaults
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=deconcentrator
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    secrets:
      - postgres-passwd
    volumes:
      - postgres:/var/lib/postgresql

networks:
  internal:

secrets:
  secret-key:
    file: secret.key

  postgres-passwd:
    file: postgres.passwd

volumes:
  postgres:
  static:

