---
- hosts: all
  remote_user: root
  gather_facts: False

  tasks:
  - name: py2
    raw: test -e /usr/bin/python || (sudo apt-get -y update && sudo apt-get install -y python-minimal)
  - include: tasks/pubkeys.yml
  - include: tasks/openssh.yml
  - include: tasks/user.yml
  - include: tasks/docker.yml
  - include: tasks/git.yml
  - include: tasks/denyhosts.yml
  - include: tasks/unattendedupgrades.yml

  handlers:
  - name: restart ssh
    service: name=ssh state=restarted


