# Generated by Django 2.2.9 on 2020-01-23 22:01

import autoslug.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import objectives.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('c', 'created'), ('q', 'queued'), ('p', 'processing'), ('e', 'error'), ('f', 'finished')], default='c', editable=False, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('package', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=20)),
                ('ident', autoslug.fields.AutoSlugField(editable=False, populate_from=objectives.models._pmm_populate, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('package', 'method')},
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('package', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=20)),
                ('ident', autoslug.fields.AutoSlugField(editable=False, populate_from=objectives.models._pmm_populate, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('package', 'method')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='objectives.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('ident', autoslug.fields.AutoSlugField(editable=False, populate_from='name', primary_key=True, serialize=False)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='a list of arguments to pass to the method.')),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='a dict of keyword arguments to pass to the method.')),
                ('method', models.ForeignKey(help_text='the function to use for this provider.', on_delete=django.db.models.deletion.CASCADE, to='objectives.Method')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='a list of arguments to pass to the strategy.')),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='a dict of keyword arguments to pass to the strategy.')),
                ('state', models.CharField(choices=[('c', 'created'), ('q', 'queued'), ('p', 'processing'), ('e', 'error'), ('f', 'finished')], default='c', editable=False, max_length=1)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectives.Strategy')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='objectives.Objective'),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectives.Provider'),
        ),
    ]
