- name: check docker existance
  stat:
    path: /usr/bin/dockerd
  register: dockerd_path

- name: install docker dependencies
  apt:
    name: "{{ packages }}"
  vars:
     packages:
       - apt-transport-https
       - ca-certificates
       - curl
       - gnupg-agent
       - software-properties-common

- name: docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: add docker rpeo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes


- name: install docker
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce 
      - docker-ce-cli

- name: set up docker/daemon.json config file
  copy:
    src: files/docker/daemon.json
    dest: /etc/docker/daemon.json
  when: dockerd_path.stat.exists

- name: restart docker
  service: name=docker state=restarted
 
- name: install docker-compose
  get_url: 
     url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
     dest: /usr/local/bin/docker-compose
     mode: '0755'
